name: Plaps's Blog
url: 'plaps153.github.io'
description: 'Notes and thoughts'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Hwangho Kim'
disqus_shortname: plaps153
google_analytics: UA-42209870-1

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed
